### ISSUE TITLE
공인인증서 종류 식별 가능할까요?

### ISSUE THREAD

**Issue by youngrok** [bandoche/PyPinkSign#10]
공인인증서의 종류가 용도에 따라 전자세금용, 은행용, 범용으로 나뉘고, 발급 대상에 따라 사업자와 개인으로 나뉘는데, 이런 정보도 식별이 가능할까요? `pub_cert.extensions` 안에 있나 싶어서 살펴봤는데 거기서는 보이지 않더군요. 인증서 관리자 등에서 보이는 걸로 봐서 인증서 자체에 담겨 있는 것 같은데 이 정보를 식별하려면 어떻게 하면 될까요?

**Comment by bandoche** [comment]
안녕하세요.
실제로 인증서 정보에는 은행용, 세금계산서용, 범용등에 대한 구분이 직접적으로는 없습니다. oid를 통해서 유추하는 수 밖에 없습니다.
해당 oid에 대한 가장 최신 정보 또한 각 인증기관에서 안내하는 문서를 찾아 확인하는 수 밖에 없습니다.
하지만 가장 최근 정보가 아니어도 상관없다면, 관련된 참고할 코드들은 GitHub 내에도 많이 있습니다.
https://github.com/search?q=%221.2.410.200004.5.2.1.1%22&type=Code

수동으로 해당 공인인증서 별로 용도 구분 매핑해서 사용하시는게 현재는 가장 현실적인 방법입니다.
