### ISSUE TITLE
이 프로젝트는 서버에 저장된 인증서만을 다룰 수 있는건가요?

### ISSUE THREAD

**Issue by SeongIkKim** [bandoche/PyPinkSign#11]
서버 내부에 존재하는 공인인증서 파일만을 다룰 수 있는건지 궁금합니다.

은행에서 사용하는 공인인증서 로그인 기능처럼 웹 서버에 이용자가 파일을 업로드하면 공인인증서 파일을 열고 로그인 정보를 저장할 수도 있을까요?

이 방식은 보안이 문제가 될까요?

**Comment by bandoche** [comment]
안녕하세요. 프로젝트에 관심 가져주셔서 감사합니다.
이 프로젝트의 목적은 공인인증서 파일을 파싱하고 특정 기능을 구현하는데 있습니다.
서버 내부의 공인인증서나, 은행에서와 같이 웹을 통해서 사용하게하는데 제약은 없습니다. 다만 뒤에서 말씀하신 방법으로 사용하시려면 프론트단에서 백(서버)로 인증서 데이터를 보내줘야됩니다.
즉 일반적인 공인인증서 보안 프로그램과 같이 인증서 선택하는 화면을 띄우는 등의 기능을 제공하는 것은 아닙니다. 
보안상의 문제에 대해서는 별도로 고민해보셔야될 것 같습니다. 단순히 파일을 보내는 것이 위험한지에 대해서는 판단이 어렵습니다. 실제로 어떻게 구현되고 관리되는지에 따라 보안상 문제여부가 달라질 수 있습니다.

**Comment by SeongIkKim** [comment]
빠른 답변 감사드립니다!
