### ISSUE TITLE
No module named 'pyasn1'

### ISSUE THREAD

**Issue by jaehyunjung83** [bandoche/PyPinkSign#16]
안녕하세요.
재미있는 프로젝트 형성과 기여에 author와 paticipants 모두에 감사드립니다.

초보 파이썬 유저라 기본적인 문제에 봉착하였는데

test_pinkSign.py와 pypinkisgn.py에서
from pyasn1.codec.der import decoder as der_decoder
를 가져오는 과정에서 
$ No module named 'pyasn1' 와
$ Tuple expression not allowed in type annotation
  Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type
(이건 datetime관련 오류라 별도 문제인 것 같습니다.)
와 같은 오류가 발생합니다.

모델을 못 찾거나 resolution 오류가 있는 경우 path 및 settings.json 관련 문제인 경우가 대부분이던데
.vscode도 pypinksign project 상위에 제대로 위치해있고
setup.py 등에도 from 모듈은 모두 install 되어있는 걸 확인하였습니다.
(conda env 사용 중이며 python version==3.8.5 64-bit입니다.)

pyasn1 git 에서 봐도 모두 맞게 되어있고 class도 맞게 가져오는 것 같아서 도무지 이유를 모르겠습니다.^^

**Comment by bandoche** [comment]
아 pip로 설치하지 않고 소스코드를 그대로 열어보신 것인가요? 
모듈 설치가 아니라 코드를 직접 호출하신다면 import issue 로 /pypinksign 를 module root 로 인식시키고 작업하셔야됩니다.
또한 asn.1 도 올바르게 package install과정을 안거쳐서 설치가 누락된게 아닌가 싶습니다. python setup.py install 을 통해 필요 의존 패키지를 설치하시거나, 수동으로 아래 패키지를 설치하시면 됩니다.
        'pyasn1==0.4.8',
        'cryptography==3.3.2',

**Comment by jaehyunjung83** [comment]
안녕하세요. 빠른 회신과 검토 감사합니다.

conda사용시 설치 패키지 인식 방법에 무지가 있어서 오류가 있었던 것 같습니다.
답변 주신내용 토대로 알아본 결과,
(mac) conda 설치경로인 
'''
/Users/***/opt/anaconda3/envs/pypinksign/lib/python3.8/site-packages/pypinksign/test_pinkSign.py"
'''
여기로 git clone하고 conda에 package들을 설치하니 문의드린 패키지 인식 문제는 해결되었습니다.

답변에 감사드립니다.

그런데 pinksing은 공인인증서를 이용한 로그인 인증 일련의 프로세스 중 어느 부분에 해당하는 내용인지 간략히 답변해주실 수 있을까요?

제가 인지하고 있는 process는

1. 각 금융사 혹은 공공기관에서 사용자가 인증 요청 시 
2. 공인인증모듈을 통해 각 사용자의 클라이언트에서 127.0.01  host server를 실행시키고
3. 인증서 인증절차에서 요구되는 5가지 값(r, n, p, q, d)을 post로 실어서 CA에보내고
4. 인증서 CA기관에서 해당 검증값(true, false)을 각 금융사 혹은 공공기관에 보내주고
5. 각 금융사 혹은 공공기관은 인증완료 세션 토큰값을 사용자 클라이언트 쿠키에 보내준다

인데,

제가 전체 코드를 다 이해하지 못해서 짐작해보건데 pinksign은 3번 중 '인증서 인증절차에서 요구되는 5가지 값(r, n, p, q, d)을' 찾아만 주는 라이브러리이고 "실어서 보내는" 절차는 생략되어있는 것으로 보면 될까요?

특정 url로 보내는 내용이나 url 설정 내용을 확인하지 못해 다시 문의드립니다.🌝

유의미한 공개 프로젝트에 감사말씀 다시 드립니다.~🗿

**Comment by bandoche** [comment]
네 짐작하시는 바가 맞습니다. 공동인증서(구, 공인인증서)파일에서 실제 키 값을 추출하고 간단한 서명 정도까지 커버하고있습니다.
즉 외부로 통신하여 인증서의 정합성이나 유효성을 검증하거나, 외부 기관(금융사 등)에 직접 로그인하는 부분은 없습니다.
