### ISSUE TITLE
choose_cert() 

### ISSUE THREAD

**Issue by dkslss** [bandoche/PyPinkSign#19]
안녕하세요. 
 cert = PinkSign(pubkey_path="%s/signCert.der" % cert_path)
 cert.prikey_path = "%s/signPri.key" % cert_path
 위부분에서 print() 해서 주소를 탐색기창에 입력하면  잘뜨는데 
 cert_list.append(cert) 여기서 리스트에 담기질않아요 ... 왜그런걸까요?

**Comment by bandoche** [comment]
리스트에 담기지 않는 다는 표현을 정확히 이해 못했습니다. 에러가 나거나, 원하는 결과와 다른 결과를 보여주는 코드를 공유해주시면 감사하겠습니다.

**Comment by dkslss** [comment]
안녕하세요 답장해주셔서 감사합니다 
실행
 
 
 
 
결과
 
 
빨간선 부분이 실행되었는데요 cert_list에 안담겨요(cert_list.append(cert))  EX) if cn is not None: ~return cert 까지사이에서 
-----Original Message-----

**Comment by bandoche** [comment]
올려주신 실행/결과 사이에 사진 또는 소스코드가 보이지 않는데 확인해주실 수 있을까요?

**Comment by dkslss** [comment]
안녕하세요  
 순서대로 1번 2번 파일입니다 
 또질문이하나더있는데요 
sign = p.sign(b'1') - verify = p.verify(sign, b'1') # True envelop = p.pkcs7_signed_msg(b'message') # PKCS7 signed with K-PKI위코드에서 '1'이 무엇을의미하나요 ? 어떤값을집어넣으라는것인지 모르겠습니다.
-----Original Message-----

**Comment by bandoche** [comment]
아... 아마도 이메일로 회신 주신 내용 중 첨부파일이 GitHub Isssue 에 올바르게 보이지 않는 것 같습니다.
실제 페이지 (https://github.com/bandoche/PyPinkSign/issues/19) 에 오셔서 다시 확인 부탁드립니다.

또한, sign 함수의 b'1'은 b'1'이라는 데이터에 개인키로 서명하여 그 결과를 반환합니다.
즉 서명하고 싶은 데이터를 입력하시면 됩니다.
(공개키의 서명에 관해서는 https://en.wikipedia.org/wiki/Digital_signature 링크를 참고해주세요.)

**Comment by dkslss** [comment]
네 감사합니다 
sign 함수에  서명하고 싶은 데이터 p.sign(b'key')이렇게 입력해봤는데  
 raise ValueError("Private key is required for signing.") 이런 에러가  발생했는데  맞는건가요? 
첨부파일은 git에서 다시 올려드립니다
![다운로드1](https://user-images.githubusercontent.com/53594802/142998676-abcad701-1ee5-4e87-97f3-ce60b60a6b5f.png)
![다운로드2](https://user-images.githubusercontent.com/53594802/142998684-6505aca7-17b6-4a81-a92c-53dd1bc5efb9.png)
.

**Comment by dkslss** [comment]
> 아... 아마도 이메일로 회신 주신 내용 중 첨부파일이 GitHub Isssue 에 올바르게 보이지 않는 것 같습니다. 실제 페이지 (#19) 에 오셔서 다시 확인 부탁드립니다.
> 
> 또한, sign 함수의 b'1'은 b'1'이라는 데이터에 개인키로 서명하여 그 결과를 반환합니다. 즉 서명하고 싶은 데이터를 입력하시면 됩니다. (공개키의 서명에 관해서는 https://en.wikipedia.org/wiki/Digital_signature 링크를 참고해주세요.

sign 함수 결과값을  TRUE로 받으면 서명이 된건가요?

**Comment by bandoche** [comment]
> sign 함수 결과값을 TRUE로 받으면 서명이 된건가요?

아니요. sign 함수의 결과값은 서명된 데이터(binary)입니다.

> sign 함수에 서명하고 싶은 데이터 p.sign(b'key')이렇게 입력해봤는데
> raise ValueError("Private key is required for signing.") 이런 에러가 발생했는데 맞는건가요?

공인인증서의 개인키와 비밀번호를 올바르게 load하기 전에 서명을 시도하면 위 에러가 발생합니다.

```
p.load_prikey(prikey_path="/path/signPri.key", prikey_password=b"my-0wn-S3cret")
```
처럼 개인키 로드 해주셔야됩니다.

**Comment by dkslss** [comment]
아하 감사합니다
sign = p.sign(b'key') 
verify = p.verify(sign, b'key1')  # True
envelop = p.pkcs7_signed_msg(b'key')  # PKCS7 signed with K-PKI
envelop  전자봉투? 이값을 어디로 보내야하는건가요?

**Comment by bandoche** [comment]
아마 관세 관련 비지니스를 구현하시는 것으로 보입니다. 구현하시는 바에 따라 달라질 내용이라 어디로 보내야될 데이터인지는 제가 알 수 없는 내용같습니다.
