### ISSUE TITLE
prikey_password

### ISSUE THREAD

**Issue by dkslss** [bandoche/PyPinkSign#20]
prikey_password 에   공인인증서 비밀번호를 넣는건가요? 
 넣어야되면 암호화해서 넣어야하나요?  어떻게해야하는지  설명이 필요합니다.

**Comment by bandoche** [comment]
네 공인인증서의 비밀번호를 넣습니다. 별도로 암호화하여 입력할 필요 없습니다.

https://github.com/bandoche/PyPinkSign#usage-example

의 예시를 참고하시면 좋습니다.
