### ISSUE TITLE
README.md는 더 이상 필요 없습니다

### ISSUE THREAD

**Issue by item4** [bandoche/PyPinkSign#3]
왜냐하면 `README.rst`도 GitHub이 알아서 파싱해주니까요.

**Comment by bandoche** [comment]
넵 사실 둘 중 하나만 남겨두면 되는데, PyPI에 이쁘게 하기 위해서 README.rst 로 갈지, 아니면 편한 에디터가 있는 README.md 로 갈지 고심끝에 하나 해체하도록 하겠습니다.

**Comment by bandoche** [comment]
https://github.com/bandoche/PyPinkSign/commit/eef75cbae356c7746c709e2edc8c8589a9e3872a
고심 끝에 해체하였습니다.
