### ISSUE TITLE
install error!!! 

### ISSUE THREAD

**Issue by ssifood** [bandoche/PyPinkSign#5]
아래와 같이 에러남. 
cryptography버전에러라는데 맞나요?? 해결책 부탁드립니다.

환경 ,python 2버전 , ubuntu 16버전대입니다.

install error!
in my opinion, cryptography version error.
what can i handle this erorr.
System. python 2, ubuntu 16.

Installed /usr/local/lib/python2.7/dist-packages/pypinksign-0.3-py2.7.egg
Processing dependencies for pypinksign==0.3
Searching for cryptography==1.5
Reading https://pypi.org/simple/cryptography/
Downloading https://files.pythonhosted.org/packages/6e/96/b8dab146e8be98061dae07e127f80cffa3061ab0e8da0d3d42f3308c6e91/cryptography-1.5.tar.gz#sha256=52f47ec9a57676043f88e3ca133638790b6b71e56e8890d9d7f3ae4fcd75fa24
Best match: cryptography 1.5
Processing cryptography-1.5.tar.gz
Writing /tmp/easy_install-QMtpEw/cryptography-1.5/setup.cfg
Running cryptography-1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QMtpEw/cryptography-1.5/egg-dist-tmp-Yw5h6h
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.linux-x86_64-2.7/_openssl.c:717:23: error: conflicting types for ‘ASN1_TIME_to_generalizedtime’
 ASN1_GENERALIZEDTIME *ASN1_TIME_to_generalizedtime(ASN1_TIME *,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from build/temp.linux-x86_64-2.7/_openssl.c:526:0:
/usr/local/include/openssl/asn1.h:630:23: note: previous declaration of ‘ASN1_TIME_to_generalizedtime’ was here
 ASN1_GENERALIZEDTIME *ASN1_TIME_to_generalizedtime(const ASN1_TIME *t,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c:811:6: error: conflicting types for ‘BIO_callback_ctrl’
 long BIO_callback_ctrl(
      ^~~~~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/asn1.h:16:0,
                 from build/temp.linux-x86_64-2.7/_openssl.c:526:
/usr/local/include/openssl/bio.h:570:6: note: previous declaration of ‘BIO_callback_ctrl’ was here
 long BIO_callback_ctrl(BIO *b, int cmd, BIO_info_cb *fp);
      ^~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_ASN1_STRING_data’:
build/temp.linux-x86_64-2.7/_openssl.c:13445:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   return ASN1_STRING_data(x0);
   ^~~~~~
In file included from /usr/local/include/openssl/bn.h:18:0,
                 from /usr/local/include/openssl/asn1.h:23,
                 from build/temp.linux-x86_64-2.7/_openssl.c:526:
/usr/local/include/openssl/asn1.h:554:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_ASN1_STRING_data’:
build/temp.linux-x86_64-2.7/_openssl.c:13468:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   { result = ASN1_STRING_data(x0); }
   ^
In file included from /usr/local/include/openssl/bn.h:18:0,
                 from /usr/local/include/openssl/asn1.h:23,
                 from build/temp.linux-x86_64-2.7/_openssl.c:526:
/usr/local/include/openssl/asn1.h:554:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_f_buffer’:
build/temp.linux-x86_64-2.7/_openssl.c:14808:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_f_buffer();
          ^~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_f_buffer’:
build/temp.linux-x86_64-2.7/_openssl.c:14818:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_f_buffer(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_f_null’:
build/temp.linux-x86_64-2.7/_openssl.c:14832:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_f_null();
          ^~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_f_null’:
build/temp.linux-x86_64-2.7/_openssl.c:14842:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_f_null(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_s_fd’:
build/temp.linux-x86_64-2.7/_openssl.c:16261:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_s_fd();
          ^~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_s_fd’:
build/temp.linux-x86_64-2.7/_openssl.c:16271:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_s_fd(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_s_file’:
build/temp.linux-x86_64-2.7/_openssl.c:16285:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_s_file();
          ^~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_s_file’:
build/temp.linux-x86_64-2.7/_openssl.c:16295:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_s_file(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_s_mem’:
build/temp.linux-x86_64-2.7/_openssl.c:16309:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_s_mem();
          ^~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_s_mem’:
build/temp.linux-x86_64-2.7/_openssl.c:16319:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_s_mem(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_s_null’:
build/temp.linux-x86_64-2.7/_openssl.c:16333:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_s_null();
          ^~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_s_null’:
build/temp.linux-x86_64-2.7/_openssl.c:16343:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_s_null(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_BIO_s_socket’:
build/temp.linux-x86_64-2.7/_openssl.c:16357:10: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   return BIO_s_socket();
          ^~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_BIO_s_socket’:
build/temp.linux-x86_64-2.7/_openssl.c:16367:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   { result = BIO_s_socket(); }
            ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_DTLSv1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22839:3: warning: ‘DTLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
   return DTLSv1_client_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1863:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_DTLSv1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22849:3: warning: ‘DTLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
   { result = DTLSv1_client_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1863:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_DTLSv1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22863:3: warning: ‘DTLSv1_method’ is deprecated [-Wdeprecated-declarations]
   return DTLSv1_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1861:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_DTLSv1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22873:3: warning: ‘DTLSv1_method’ is deprecated [-Wdeprecated-declarations]
   { result = DTLSv1_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1861:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_DTLSv1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22887:3: warning: ‘DTLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   return DTLSv1_server_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1862:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_DTLSv1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:22897:3: warning: ‘DTLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   { result = DTLSv1_server_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1862:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_OPENSSL_config’:
build/temp.linux-x86_64-2.7/_openssl.c:39568:3: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
   OPENSSL_config(x0);
   ^~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/conf.h:91:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_OPENSSL_config’:
build/temp.linux-x86_64-2.7/_openssl.c:39590:3: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
   { OPENSSL_config(x0); }
   ^
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/conf.h:91:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52764:3: warning: ‘TLSv1_1_client_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_1_client_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1851:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52774:3: warning: ‘TLSv1_1_client_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_1_client_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1851:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52788:3: warning: ‘TLSv1_1_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_1_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1849:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52798:3: warning: ‘TLSv1_1_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_1_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1849:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52812:3: warning: ‘TLSv1_1_server_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_1_server_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1850:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52822:3: warning: ‘TLSv1_1_server_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_1_server_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1850:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_2_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52836:3: warning: ‘TLSv1_2_client_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_2_client_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1857:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_2_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52846:3: warning: ‘TLSv1_2_client_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_2_client_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1857:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_2_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52860:3: warning: ‘TLSv1_2_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_2_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1855:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_2_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52870:3: warning: ‘TLSv1_2_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_2_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1855:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_2_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52884:3: warning: ‘TLSv1_2_server_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_2_server_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1856:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_2_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52894:3: warning: ‘TLSv1_2_server_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_2_server_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1856:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52908:3: warning: ‘TLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_client_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1845:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_client_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52918:3: warning: ‘TLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_client_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1845:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52932:3: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1843:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52942:3: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1843:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_TLSv1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52956:3: warning: ‘TLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   return TLSv1_server_method();
   ^~~~~~
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1844:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_TLSv1_server_method’:
build/temp.linux-x86_64-2.7/_openssl.c:52966:3: warning: ‘TLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   { result = TLSv1_server_method(); }
   ^
In file included from /usr/local/include/openssl/cterr.h:14:0,
                 from /usr/local/include/openssl/ct.h:19,
                 from /usr/local/include/openssl/ssl.h:31,
                 from build/temp.linux-x86_64-2.7/_openssl.c:610:
/usr/local/include/openssl/ssl.h:1844:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_X509_CRL_get_lastUpdate’:
build/temp.linux-x86_64-2.7/_openssl.c:54001:3: warning: ‘X509_CRL_get_lastUpdate’ is deprecated [-Wdeprecated-declarations]
   return X509_CRL_get_lastUpdate(x0);
   ^~~~~~
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:727:1: note: declared here
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_lastUpdate(X509_CRL *crl))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_X509_CRL_get_lastUpdate’:
build/temp.linux-x86_64-2.7/_openssl.c:54024:3: warning: ‘X509_CRL_get_lastUpdate’ is deprecated [-Wdeprecated-declarations]
   { result = X509_CRL_get_lastUpdate(x0); }
   ^
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:727:1: note: declared here
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_lastUpdate(X509_CRL *crl))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_X509_CRL_get_nextUpdate’:
build/temp.linux-x86_64-2.7/_openssl.c:54037:3: warning: ‘X509_CRL_get_nextUpdate’ is deprecated [-Wdeprecated-declarations]
   return X509_CRL_get_nextUpdate(x0);
   ^~~~~~
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:728:1: note: declared here
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_X509_CRL_get_nextUpdate’:
build/temp.linux-x86_64-2.7/_openssl.c:54060:3: warning: ‘X509_CRL_get_nextUpdate’ is deprecated [-Wdeprecated-declarations]
   { result = X509_CRL_get_nextUpdate(x0); }
   ^
In file included from /usr/local/include/openssl/x509_vfy.h:20:0,
                 from /usr/local/include/openssl/x509.h:320,
                 from /usr/local/include/openssl/cms.h:16,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:728:1: note: declared here
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
 ^
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_X509_get0_signature’:
build/temp.linux-x86_64-2.7/_openssl.c:59497:23: warning: passing argument 1 of ‘X509_get0_signature’ from incompatible pointer type [-Wincompatible-pointer-types]
   X509_get0_signature(x0, x1, x2);
                       ^~
In file included from /usr/local/include/openssl/cms.h:16:0,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:571:6: note: expected ‘const ASN1_BIT_STRING ** {aka const struct asn1_string_st **}’ but argument is of type ‘ASN1_OCTET_STRING ** {aka struct asn1_string_st **}’
 void X509_get0_signature(const ASN1_BIT_STRING **psig,
      ^~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c:59497:27: warning: passing argument 2 of ‘X509_get0_signature’ from incompatible pointer type [-Wincompatible-pointer-types]
   X509_get0_signature(x0, x1, x2);
                           ^~
In file included from /usr/local/include/openssl/cms.h:16:0,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:571:6: note: expected ‘const X509_ALGOR ** {aka const struct X509_algor_st **}’ but argument is of type ‘X509_ALGOR ** {aka struct X509_algor_st **}’
 void X509_get0_signature(const ASN1_BIT_STRING **psig,
      ^~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_X509_get0_signature’:
build/temp.linux-x86_64-2.7/_openssl.c:59549:25: warning: passing argument 1 of ‘X509_get0_signature’ from incompatible pointer type [-Wincompatible-pointer-types]
   { X509_get0_signature(x0, x1, x2); }
                         ^~
In file included from /usr/local/include/openssl/cms.h:16:0,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:571:6: note: expected ‘const ASN1_BIT_STRING ** {aka const struct asn1_string_st **}’ but argument is of type ‘ASN1_OCTET_STRING ** {aka struct asn1_string_st **}’
 void X509_get0_signature(const ASN1_BIT_STRING **psig,
      ^~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-2.7/_openssl.c:59549:29: warning: passing argument 2 of ‘X509_get0_signature’ from incompatible pointer type [-Wincompatible-pointer-types]
   { X509_get0_signature(x0, x1, x2); }
                             ^~
In file included from /usr/local/include/openssl/cms.h:16:0,
                 from build/temp.linux-x86_64-2.7/_openssl.c:541:
/usr/local/include/openssl/x509.h:571:6: note: expected ‘const X509_ALGOR ** {aka const struct X509_algor_st **}’ but argument is of type ‘X509_ALGOR ** {aka struct X509_algor_st **}’
 void X509_get0_signature(const ASN1_BIT_STRING **psig,
      ^~~~~~~~~~~~~~~~~~~
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by bandoche** [comment]
libssl-dev (openssl.h) 버전이 우분투 패키지 말고 별도로 업데이트 하신거랑 안맞는거 아닌지 확인 부탁드릴게요. 새로 16.04 가상머신 설치하고, python(2.7)/python-pip 설치하고 apt install libssl-dev 설치 이후에 pip install pypinksign 설치 성공했습니다.
