### ISSUE TITLE
안녕하세요 질문좀해도될까요??ㅜㅜ

### ISSUE THREAD

**Issue by Jinteger** [bandoche/PyPinkSign#6]
일단 python 2.~ 버전에만 되는건가요??
현재 3.6 버전입니다
pypinksign 설치했는데
뭔가 모듈들이 버전이 안맞다고난리네요 ㅜㅜ

pyasn1-modules 요놈이랑  pyasn1 요놈이랑

그리고 
import pypinksign 이거 하니까 
ModuleNotFoundError: No module named 'rsassa_pkcs1_v15'
이게 뜨네요 ㅠㅠ 
'이놈에 대한건 아무리검색해봐도 정보를못찾겠던데

최종적으로 버전문제인가요???

**Comment by bandoche** [comment]
네 지금 pip로 배포된 버전은 2.7용인데 master 브랜치는 3.6~ 용으로 변경했습니다. 변경이 좀 있긴 하지만 master 기준으로 쓰시면 될거같습니다.

**Comment by Jinteger** [comment]
감사합니다 .
뒤늦게 깨닫고 수정하였습니다.
그런데
518 줄
t = sha1(password + salt).digest()
부분에서
해당 에러가 발생합니다.
TypeError: must be str, not bytes
혹시 괜찮으시다면 답변좀 부탁드리겠습니다 ㅠㅠ

**Comment by Jinteger** [comment]
답변감사합니다.
