### ISSUE TITLE
p12 파일을 load할 때 r value가 추출되지 않음

### ISSUE THREAD

**Issue by 0xk0ff33** [bandoche/PyPinkSign#9]
안녕하세요, 먼저 재미있는 프로젝트를 공유해주셔서 감사합니다.

p12/pfx 파일을 가지고 테스트해보는 중인데, 도저히 실마리가 안보여서 남겨봅니다.

p12파일로 시작하게되면 `separate_p12_into_npki` 함수로 가서 private key가 dump되어 나오게 되는데요.

이 데이터는 마치 r value가 있는 부분이 짤린 것 처럼 추출이 되더라구요.

r value를 injection하는 코드가 있던데 혹시 관련이 있는 것 인가요?

**Comment by bandoche** [comment]
네 그렇습니다.
정확하게 표준 규격을 찾아보지는 못하였는데, p12/pfx 파일을 openssl을 통해 개인키/공개키로 분리할 때 r 값이 개인키 안에 들어가지 않고 stdout으로 부가 값으로 나오는 것을 확인했습니다. 
p12/pfx를 다시 signCert.der,signPri.key 파일로 분리하여 저장하려면 signPri.key 데이터에 inject하는 코드를 활용하여 r값을 주입한 다음 저장해야 정상적으로 처리됩니다. 그렇지 않으면 r값이 빠진 signPri.key 파일이 생성됩니다.
